p6df::init() {

  mkdir -p /tmp/p6
  p6df::init::files_load
  p6df::core::main::init
}

p6df::init::files_load() {

  local file
  for file in $P6_DFZ_LIB_DIR/*.zsh; do
    # chicken-in-egg - intentionally not p6df::util::file::load
    . $file
  done
}

p6df::init
